name: Delete CodePush
description: Delete a CodePush deployment track
author: huextrat

inputs:
  token:
    description: "AppCenter API token"
    required: true
  app:
    description: "AppCenter app name"
    required: true
  deploymentTrack:
    description: "AppCenter deployment track"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4.0.4
      with:
        node-version: 18.15.0
    - name: 📦 Install App Center cli
      run: npm install -g appcenter-cli@2.14.0
      shell: bash
    - name: 🔑 Login App Center cli
      run: npx appcenter login --token ${{ inputs.token }}
      shell: bash
    - name: 🥇 Set current AppCenter app
      run: npx appcenter apps set-current ${{ inputs.app }}
      shell: bash
    - name: 🧑‍⚖️ Delete CodePush Track
      run: yes | npx appcenter codepush deployment remove ${{ inputs.deploymentTrack }}
      shell: bash

branding:
  icon: delete
  color: red
